    name: Build and Scan
    on: [push]
 
    jobs:
        build:
            runs-on: ubuntu-latest
            steps:
            - name: Build the Docker Image
              run: docker build . --tag sysdiglabs/dummy-vuln-app:latest
            - name: Scan Image
              uses: sysdiglabs/scan-action@v3
              with:
                image-tag: "sysdiglabs/dummy-vuln-app:latest"
                sysdig-secure-token: ${{ secrets.SYSDIG_INLINE_SCAN }}
