    ...

    name: build and scan Docker image
    on:[push]
    jobs:
        build:
            run-on: ubuntu-latest
            steps:
            - name: Build the Docker Image
              run: docker build . --file Dockerfile --tag sysdiglabs/dummy-vuln-app:latest
            - name: Scan Image
              uses: sysdiglabs/scan-action@v3
              with:
                image-tag: "sysdiglabs/dummy-vuln-app:latest"
                sysdig-secure-token: ${{ secrets.SYSDIG_INLINE_SCAN }}
